"""
Django settings for WebSongHong project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Nạp biến từ file .env (nếu có). Biến môi trường thật của server luôn được ưu tiên.
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    for _line in _env_file.read_text(encoding='utf-8').splitlines():
        _line = _line.strip()
        if _line and not _line.startswith('#') and '=' in _line:
            _key, _value = _line.split('=', 1)
            _key = _key.strip()
            if not os.environ.get(_key):
                os.environ[_key] = _value.strip().strip('"').strip("'")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY') or 'django-insecure-dev-only-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = ['*', 'keovuasonghong.vn', 'www.keovuasonghong.vn', '192.168.1.122', '127.0.0.1', 'localhost']

CSRF_TRUSTED_ORIGINS = [
    'https://keovuasonghong.vn',
    'https://www.keovuasonghong.vn',
    'http://keovuasonghong.vn',
    'http://www.keovuasonghong.vn',
    'http://192.168.1.122:8000',
    'http://192.168.1.122',
    'http://127.0.0.1:8000',
    'http://127.0.0.1',
    'http://localhost:8000',
    'http://localhost',
    'https://*.trycloudflare.com',
    'https://*.pinggy.link',
    'https://*.ngrok-free.app',
]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'cloudinary',
    'main',
]

UNFOLD = {
    "SITE_TITLE": "Keo Vữa Sông Hồng Admin",
    "SITE_HEADER": "SHK Mortar Admin",
    "SITE_URL": "/",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: "/static/images/favicon-32x32.png?v=2",
        },
        {
            "rel": "icon",
            "sizes": "192x192",
            "type": "image/png",
            "href": lambda request: "/static/images/favicon-192.png?v=2",
        },
        {
            "rel": "icon",
            "type": "image/png",
            "href": lambda request: "/static/images/favicon.png?v=2",
        },
        {
            "rel": "apple-touch-icon",
            "href": lambda request: "/static/images/favicon.png?v=2",
        },
    ],
    "SITE_SYMBOL": "speed",
    "BORDER_RADIUS": "0px",
    "STYLES": [
        "/static/css/admin_custom.css"
    ],
    "SCRIPTS": [
        "/static/js/admin_custom_delete.js",
        "/static/js/admin_brand_align.js",
        "/static/js/admin_notifications.js"
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COMMAND": {
        "search_models": True,
        "show_history": True,
    },
    "COLORS": {
        "primary": {
            "50": "255 247 237",
            "100": "255 237 213",
            "200": "254 215 170",
            "300": "253 186 116",
            "400": "251 146 60",
            "500": "249 115 22",
            "600": "234 88 12",
            "700": "194 65 12",
            "800": "154 52 18",
            "900": "124 45 18",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Quản lý hệ thống",
                "separator": True,
                "items": [
                    {
                        "title": "Sản phẩm",
                        "icon": "inventory_2",
                        "link": "/admin/main/product/",
                        "items": [
                            {
                                "title": "Danh sách sản phẩm",
                                "link": "/admin/main/product/",
                            },
                            {
                                "title": "Danh mục sản phẩm",
                                "link": "/admin/main/productcategory/",
                            },
                        ],
                    },
                    {
                        "title": "Dự án",
                        "icon": "apartment",
                        "link": "/admin/main/project/",
                        "items": [
                            {
                                "title": "Danh sách dự án",
                                "link": "/admin/main/project/",
                            },
                            {
                                "title": "Danh mục dự án",
                                "link": "/admin/main/projectcategory/",
                            },
                        ],
                    },
                    {
                        "title": "Tin tức",
                        "icon": "newspaper",
                        "link": "/admin/main/news/",
                        "items": [
                            {
                                "title": "Danh sách tin tức",
                                "link": "/admin/main/news/",
                            },
                            {
                                "title": "Danh mục tin tức",
                                "link": "/admin/main/newscategory/",
                            },
                        ],
                    },
                    {
                        "title": "Đại lý phân phối",
                        "icon": "storefront",
                        "link": "/admin/main/distributor/",
                        "items": [
                            {"title": "Danh sách đại lý", "link": "/admin/main/distributor/"},
                            {"title": "Danh mục đại lý", "link": "/admin/main/distributordetail/"},
                        ],
                    },
                    {
                        "title": "E-catalog",
                        "icon": "menu_book",
                        "link": "/admin/main/catalogue/",
                    },
                    {
                        "title": "Công cụ tính",
                        "icon": "calculate",
                        "link": "/cong-cu-tinh/",
                    },
                    {
                        "title": "Đăng ký đại lý",
                        "icon": "how_to_reg",
                        "link": "/admin/main/dealerregistration/",
                        "badge": "main.admin_badges.dealer_registration_badge",
                        "badge_style": "solid",
                    },
                    {
                        "title": "Đăng ký tư vấn",
                        "icon": "support_agent",
                        "link": "/admin/main/consultationrequest/",
                        "badge": "main.admin_badges.consultation_request_badge",
                        "badge_style": "solid",
                    },
                ],
            },
            {
                "title": "Kênh bán hàng",
                "separator": True,
                "items": [
                    {
                        "title": "Giao diện",
                        "icon": "palette",
                        "link": "/admin/main/themesettings/",
                    },
                ],
            },
        ],
    },
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'main.middleware.NonWwwRedirectMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'main.middleware.LegacyRedirectMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'
# Mặc định Django là 'same-origin' (không gửi Referer sang trang khác) nên video YouTube nhúng báo lỗi 153
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

ROOT_URLCONF = 'WebSongHong.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.theme_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'WebSongHong.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Phục vụ static trực tiếp (không cần collectstatic; lệnh này bị lỗi do cloudinary_storage + Django 6)
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── CLOUDINARY STORAGE ───────────────────────────────────────────
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'gesmsoc5',
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# ── EMAIL CONFIGURATION (Gmail SMTP) ──────────────────────────────
# Hướng dẫn tạo App Password:
# 1. Vào https://myaccount.google.com/security
# 2. Bật "Xác minh 2 bước" nếu chưa bật
# 3. Tìm "Mật khẩu ứng dụng" (App passwords)
# 4. Chọn ứng dụng: Mail / Other, đặt tên "SHK Website"
# 5. Copy 16 ký tự được tạo ra → điền vào EMAIL_HOST_PASSWORD bên dưới

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'admin@keovuasonghong.vn'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = 'SHK Mortar <admin@keovuasonghong.vn>'

# Email nhận thông báo đăng ký
NOTIFY_EMAIL = 'admin@keovuasonghong.vn'

# Chatbox AI (Claude)
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
CHATBOT_MODEL = os.environ.get('CHATBOT_MODEL', 'claude-opus-5-5')
