# Generated by Django 6.1.1 on 2026-09-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_news_options_alter_project_options_news_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributor',
            options={'ordering': ['order', 'province', 'name'], 'verbose_name': 'Đại lý phân phối', 'verbose_name_plural': 'Đại lý phân phối'},
        ),
        migrations.AddField(
            model_name='distributor',
            name='address_type',
            field=models.CharField(choices=[('headquarters', 'Địa chỉ trụ sở'), ('distribution_area', 'Khu vực phân phối')], default='headquarters', max_length=50, verbose_name='Loại địa chỉ'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='hotline_label',
            field=models.CharField(blank=True, default='HOTLINE TƯ VẤN & MUA HÀNG', max_length=100, verbose_name='Tiêu đề Hotline/Liên hệ'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='map_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Địa chỉ tìm kiếm trên Google Maps'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, verbose_name='Kênh TikTok'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Kênh YouTube'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ / Khu vực phân phối'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hiển thị'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Tên đại lý / Công ty'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='phone',
            field=models.CharField(max_length=300, verbose_name='Số điện thoại / Hotline'),
        ),
    ]
