# Generated by Django 6.1.1 on 2026-09-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_distributor_options_distributor_address_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='google_maps_link',
            field=models.TextField(blank=True, help_text='Dán link chia sẻ từ Google Maps (chứa toạ độ @lat,lng) hoặc mã nhúng iframe lấy từ Google Maps > Chia sẻ > Nhúng bản đồ. Nếu để trống, hệ thống sẽ tự tìm theo địa chỉ ở trên.', null=True, verbose_name='Link Google Maps'),
        ),
    ]
