# Generated by Django 6.1.1 on 2026-09-10 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_distributor_google_maps_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='VD: Facebook, Zalo, Instagram...', max_length=100, verbose_name='Tên nền tảng')),
                ('url', models.URLField(max_length=500, verbose_name='Đường dẫn')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_links', to='main.distributor', verbose_name='Đại lý')),
            ],
            options={
                'verbose_name': 'Liên kết khác',
                'verbose_name_plural': 'Liên kết khác',
                'ordering': ['order', 'id'],
            },
        ),
    ]
