# Generated by Django 6.1.1 on 2026-09-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_distributorlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'verbose_name': 'Tin tức', 'verbose_name_plural': 'Tin tức'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-published_at'], 'verbose_name': 'Dự án', 'verbose_name_plural': 'Dự án'},
        ),
    ]
