# Generated by Django 6.1.1 on 2026-09-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_news_options_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributor',
            options={'ordering': ['province', 'name'], 'verbose_name': 'Đại lý phân phối', 'verbose_name_plural': 'Đại lý phân phối'},
        ),
    ]
