# Generated by Django 6.1.1 on 2026-09-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_distributor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Loại catalogue'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='group_name',
            field=models.CharField(choices=[('Hồ sơ năng lực', 'Hồ sơ năng lực'), ('Tài liệu vữa khô trộn sẵn', 'Tài liệu vữa khô trộn sẵn'), ('Tài liệu vữa dành cho gạch AAC', 'Tài liệu vữa dành cho gạch AAC'), ('Tài liệu keo dán gạch', 'Tài liệu keo dán gạch'), ('Tài liệu cát sấy khô', 'Tài liệu cát sấy khô')], default='Hồ sơ năng lực', max_length=255, verbose_name='Tên nhóm tài liệu'),
        ),
    ]
