# Generated by Django 6.1.1 on 2026-09-12 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_catalogue_category_alter_catalogue_group_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order'], 'verbose_name': 'Banner trang chủ', 'verbose_name_plural': 'Banner trang chủ'},
        ),
        migrations.AlterModelOptions(
            name='catalogue',
            options={'ordering': ['group_name', 'order', 'title'], 'verbose_name': 'E-Catalog', 'verbose_name_plural': 'E-Catalog'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tin nhắn liên hệ', 'verbose_name_plural': 'Tin nhắn liên hệ'},
        ),
        migrations.AlterModelOptions(
            name='themesettings',
            options={'verbose_name': 'Cài đặt Giao diện & Logo', 'verbose_name_plural': 'Cài đặt Giao diện & Logo'},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Công ty TNHH Keo Vữa Sông Hồng', max_length=255, verbose_name='Họ và tên')),
                ('phone', models.CharField(blank=True, default='0938016788', max_length=50, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, default='admin@keovuasonghong.vn', max_length=254, verbose_name='Email')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], default='Nam', max_length=20, verbose_name='Giới tính')),
                ('region', models.CharField(blank=True, default='Hưng Yên - Huyện Khoái Châu', max_length=255, verbose_name='Khu vực')),
                ('ward', models.CharField(blank=True, default='Xã Đông Ninh', max_length=255, verbose_name='Phường/Xã')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ tài khoản',
                'verbose_name_plural': 'Hồ sơ tài khoản',
            },
        ),
    ]
