# Generated by Django 6.1.1 on 2026-09-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_banner_options_alter_catalogue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterField(
            model_name='distributorlink',
            name='label',
            field=models.CharField(blank=True, help_text='VD: Facebook, Zalo, Instagram...', max_length=100, verbose_name='Tên nền tảng'),
        ),
        migrations.AlterField(
            model_name='distributorlink',
            name='url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Đường dẫn'),
        ),
    ]
