# Generated by Django 6.1.1 on 2026-09-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_product_options_alter_distributorlink_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='cta_btn_link',
            field=models.CharField(blank=True, default='/dang-ky-dai-ly/', max_length=255, verbose_name='Đường dẫn nút CTA Header'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='cta_btn_text',
            field=models.CharField(blank=True, default='ĐĂNG KÝ ĐẠI LÝ', max_length=100, verbose_name='Chữ trên nút CTA Header'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_company_name',
            field=models.CharField(blank=True, default='Công ty TNHH Keo Vữa Sông Hồng', max_length=255, verbose_name='Tên công ty Footer'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='© 2026. Mọi bản quyền được bảo lưu bởi Công ty TNHH Keo Vữa Sông Hồng', max_length=255, verbose_name='Bản quyền Footer'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_group',
            field=models.URLField(blank=True, null=True, verbose_name='Link Group Facebook'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_info_html',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung tuỳ chỉnh cột công ty (HTML)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_map_iframe',
            field=models.TextField(blank=True, null=True, verbose_name='Mã nhúng iframe Google Maps'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_media_email',
            field=models.EmailField(blank=True, default='admin@keovuasonghong.vn', max_length=254, verbose_name='Email hợp tác truyền thông'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_office_address',
            field=models.CharField(blank=True, default='Vinhomes Ocean Park 2, Văn Giang, Hưng Yên', max_length=255, verbose_name='Địa chỉ văn phòng'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_shopee',
            field=models.URLField(blank=True, null=True, verbose_name='Link Shopee'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='Link TikTok'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='intro_badge',
            field=models.CharField(blank=True, default='Giới thiệu', max_length=100, verbose_name='Thẻ phụ (Badge)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='phong_su_badge',
            field=models.CharField(blank=True, default='Xem thêm', max_length=100, verbose_name='Thẻ phụ phóng sự'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='phong_su_btn_link',
            field=models.CharField(blank=True, default='/tin-tuc/?category=phong-su-thuc-te', max_length=255, verbose_name='Đường dẫn nút phóng sự'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='phong_su_btn_text',
            field=models.CharField(blank=True, default='XEM TẤT CẢ', max_length=100, verbose_name='Chữ trên nút phóng sự'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='phong_su_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả phóng sự thực tế'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='phong_su_title',
            field=models.CharField(blank=True, default='Phóng sự thực tế', max_length=255, verbose_name='Tiêu đề phóng sự'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='quality_description_html',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung tiêu chuẩn chất lượng (HTML/Văn bản)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='quality_drive_btn_text',
            field=models.CharField(blank=True, default='Tải Giấy Kiểm Nghiệm', max_length=100, verbose_name='Chữ trên nút tải chứng nhận'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='quality_drive_link',
            field=models.URLField(blank=True, null=True, verbose_name='Đường dẫn Google Drive (Hồ sơ kiểm nghiệm)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='quality_title',
            field=models.CharField(blank=True, default='Minh chứng chất lượng', max_length=255, verbose_name='Tiêu đề minh chứng chất lượng'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='show_phong_su',
            field=models.BooleanField(default=True, verbose_name='Hiển thị Module Phóng sự thực tế'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='show_quality',
            field=models.BooleanField(default=True, verbose_name='Hiển thị Module Minh chứng chất lượng'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ nhà máy'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email phòng kinh doanh'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Link Facebook Fanpage'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Link YouTube'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_zalo',
            field=models.URLField(blank=True, null=True, verbose_name='Link Zalo OA'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='header_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan / Thông báo đầu trang'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='intro_description',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung giới thiệu (HTML/Văn bản)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='intro_title',
            field=models.CharField(blank=True, default='Về chúng tôi', max_length=255, verbose_name='Tiêu đề giới thiệu'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='intro_youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link YouTube video giới thiệu'),
        ),
    ]
