# Generated by Django 6.1.1 on 2026-09-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_themesettings_cta_btn_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='hero_btn_link',
            field=models.CharField(blank=True, default='/san-pham/#plStickyNav', max_length=255, verbose_name='Đường dẫn nút Banner'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hero_btn_text',
            field=models.CharField(blank=True, default='Khám Phá Sản Phẩm', max_length=100, verbose_name='Chữ trên nút Banner'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hero_desc',
            field=models.TextField(blank=True, default='Nhà máy sản xuất vữa khô trộn sẵn, keo dán gạch chất lượng cao', verbose_name='Mô tả Banner chính'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='Công ty TNHH Keo Vữa Sông Hồng', max_length=255, verbose_name='Tiêu đề Banner chính'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hero_video_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn Video nền Banner (MP4)'),
        ),
    ]
