# Generated by Django 6.1.1 on 2026-09-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_themesettings_hero_btn_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesettings',
            name='hero_btn_link',
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hero_video_file',
            field=models.FileField(blank=True, null=True, upload_to='theme/videos/', verbose_name='Tải file Video Banner lên (.mp4)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='hero_video_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Hoặc dán đường dẫn Video nền MP4'),
        ),
    ]
