# Generated by Django 6.1.1 on 2026-09-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_themesettings_hero_btn_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='hero_btn_link',
            field=models.CharField(blank=True, default='/san-pham/#plStickyNav', max_length=255, verbose_name='Đường dẫn nút Banner'),
        ),
    ]
