# Generated by Django 6.1.1 on 2026-09-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_themesettings_hero_btn_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='intro_description',
            field=models.TextField(blank=True, default='Công ty TNHH Keo Vữa Sông Hồng là đơn vị hoạt động trong lĩnh vực sản xuất vật liệu xây dựng tại Hưng Yên. Với kinh nghiệm trong ngành cùng hệ thống dây chuyền, máy móc và công nghệ hiện đại, chúng tôi tập trung nghiên cứu và sản xuất những sản phẩm đáp ứng yêu cầu ngày càng cao của thị trường.\n\nKhông chỉ tạo ra vật liệu mới, SHK Mortar hướng tới những giải pháp phù hợp với phương thức xây dựng hiện đại – nơi chất lượng, tính ổn định và hiệu quả thi công được đặt lên hàng đầu. Mỗi sản phẩm được nghiên cứu, kiểm soát và kiểm định chặt chẽ, nhằm tạo ra giá trị thiết thực cho công trình và đối tác.\n\nVới định hướng đưa các sản phẩm chất lượng đến gần hơn với thị trường, từ dự án đến công trình dân dụng, SHK Mortar từng bước phát triển hệ giải pháp vật liệu giúp tối ưu quy trình thi công và chi phí, hướng tới một phương thức xây dựng hiệu quả hơn và tạo nên một cách tiếp cận mới cho ngành xây dựng.', null=True, verbose_name='Nội dung giới thiệu (HTML/Văn bản)'),
        ),
    ]
