# Generated by Django 6.1.1 on 2026-09-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_themesettings_intro_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='intro_youtube_url',
            field=models.CharField(blank=True, default='https://www.youtube.com/watch?v=N-FLw-piwlc', max_length=500, null=True, verbose_name='Link YouTube video giới thiệu'),
        ),
    ]
