# Generated by Django 6.1.1 on 2026-09-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_themesettings_intro_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='phong_su_desc',
            field=models.TextField(blank=True, default='Theo sát những công trình thực tế, ghi nhận câu chuyện và trải nghiệm từ thợ thi công, đại lý, nhà thầu và chủ đầu tư. Qua đó, thương hiệu giới thiệu chất lượng sản phẩm, giải pháp thi công và dấu ấn đồng hành trên từng công trình.', null=True, verbose_name='Mô tả phóng sự thực tế'),
        ),
    ]
