# Generated by Django 6.1.1 on 2026-09-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_themesettings_phong_su_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video_url',
            field=models.CharField(blank=True, help_text='Dán link YouTube video phóng sự', max_length=500, null=True, verbose_name='URL YouTube'),
        ),
    ]
