# Generated by Django 6.1.1 on 2026-09-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_news_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='quality_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/quality/', verbose_name='Ảnh chứng nhận / Minh chứng chất lượng'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='quality_description_html',
            field=models.TextField(blank=True, default='<p class="about-para">\n  SHK Mortar áp dụng hệ thống quản lý và kiểm soát chất lượng nghiêm ngặt, được kiểm định bởi các đơn vị chuyên môn.\n</p>\n\n<p class="about-para" style="margin-bottom:4px;">\n  Sản phẩm đáp ứng các tiêu chuẩn:\n</p>\n\n<ul class="quality-bullet-list">\n  <li>ISO 9001:2015 (Hệ thống quản lý chất lượng QMS)</li>\n  <li>TCVN 4314:2022 (Tiêu chuẩn Vữa xây dựng)</li>\n  <li>TCVN 7899-1:2008 (Tiêu chuẩn Keo dán gạch)</li>\n  <li>TCVN 9028:2011 (Tiêu chuẩn Vữa cho bê tông nhẹ)</li>\n</ul>\n\n<p class="about-para" style="margin-top:8px;">\n  cùng các chứng nhận và hồ sơ kiểm tra chất lượng liên quan, đảm bảo tính ổn định và tin cậy trong từng công trình.\n</p>', null=True, verbose_name='Nội dung tiêu chuẩn chất lượng (HTML/Văn bản)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='quality_drive_link',
            field=models.CharField(blank=True, default='https://drive.google.com/drive/folders/1-2VEnOxoTh2CG0laK1VURFiEDBvzOOQd?hl=vi', max_length=500, null=True, verbose_name='Đường dẫn Google Drive (Hồ sơ kiểm nghiệm)'),
        ),
    ]
