# Generated by Django 6.1.1 on 2026-09-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_themesettings_quality_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='quality_description_html',
            field=models.TextField(blank=True, default='SHK Mortar áp dụng hệ thống quản lý và kiểm soát chất lượng nghiêm ngặt, được kiểm định bởi các đơn vị chuyên môn.\n\nSản phẩm đáp ứng các tiêu chuẩn:\n- ISO 9001:2015 (Hệ thống quản lý chất lượng QMS)\n- TCVN 4314:2022 (Tiêu chuẩn Vữa xây dựng)\n- TCVN 7899-1:2008 (Tiêu chuẩn Keo dán gạch)\n- TCVN 9028:2011 (Tiêu chuẩn Vữa cho bê tông nhẹ)\n\ncùng các chứng nhận và hồ sơ kiểm tra chất lượng liên quan, đảm bảo tính ổn định và tin cậy trong từng công trình.', null=True, verbose_name='Nội dung tiêu chuẩn chất lượng (Văn bản)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='quality_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/quality/', verbose_name='Thêm ảnh chứng nhận mới vào Slider'),
        ),
    ]
