# Generated by Django 6.1.1 on 2026-09-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_themesettings_quality_description_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, help_text='Dùng khi không có sẵn file ảnh để tải lên', max_length=500, null=True, verbose_name='Link ảnh (URL)'),
        ),
    ]
