# Generated by Django 6.1.1 on 2026-09-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_news_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='footer_doc_1_link',
            field=models.CharField(blank=True, default='/catalogue/', max_length=255, verbose_name='Đường dẫn tài liệu 1'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_doc_1_title',
            field=models.CharField(blank=True, default='Chính Sách Khách Hàng', max_length=150, verbose_name='Tên tài liệu 1'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_doc_2_link',
            field=models.CharField(blank=True, default='/catalogue/', max_length=255, verbose_name='Đường dẫn tài liệu 2'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_doc_2_title',
            field=models.CharField(blank=True, default='Chính Sách Bảo Hành', max_length=150, verbose_name='Tên tài liệu 2'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_doc_3_link',
            field=models.CharField(blank=True, default='/catalogue/?doc=ho-so-nang-luc', max_length=255, verbose_name='Đường dẫn tài liệu 3'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_doc_3_title',
            field=models.CharField(blank=True, default='Hồ Sơ Năng Lực', max_length=150, verbose_name='Tên tài liệu 3'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_doc_4_link',
            field=models.CharField(blank=True, default='/catalogue/', max_length=255, verbose_name='Đường dẫn tài liệu 4'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_doc_4_title',
            field=models.CharField(blank=True, default='Hồ Sơ Kỹ Thuật', max_length=150, verbose_name='Tên tài liệu 4'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com', null=True, verbose_name='Link LinkedIn'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_address',
            field=models.CharField(blank=True, default='Thôn Ninh Tập, xã Châu Ninh, Hưng Yên', max_length=255, null=True, verbose_name='Địa chỉ nhà máy'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_email',
            field=models.EmailField(blank=True, default='kinhdoanh@keovuasonghong.vn', max_length=254, null=True, verbose_name='Email phòng kinh doanh'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_facebook',
            field=models.URLField(blank=True, default='https://www.facebook.com/keovuasonghong.vn/', null=True, verbose_name='Link Facebook Fanpage'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_group',
            field=models.URLField(blank=True, default='https://www.facebook.com/groups/4105613262904191', null=True, verbose_name='Link Group Facebook'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_map_iframe',
            field=models.TextField(blank=True, default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3730.0519155167885!2d105.9292376!3d20.7891875!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135b7ebaf798ae9%3A0x12abc2f8114a7f71!2sNh%C3%A0%20m%C3%A1y%20Keo%20V%E1%BB%AFa%20S%C3%B4ng%20H%E1%BB%93ng%20-%20SHK%20Mortar!5e0!3m2!1svi!2svn!4v1700000000000!5m2!1svi!2svn" title="Nhà máy Keo Vữa Sông Hồng - SHK Mortar" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', null=True, verbose_name='Mã nhúng iframe Google Maps'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_phone',
            field=models.CharField(blank=True, default='0938016788', max_length=50, null=True, verbose_name='SĐT footer'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_shopee',
            field=models.URLField(blank=True, default='https://shopee.vn/shop/1658539442', null=True, verbose_name='Link Shopee'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_tiktok',
            field=models.URLField(blank=True, default='https://www.tiktok.com/@shkmortar', null=True, verbose_name='Link TikTok'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_youtube',
            field=models.URLField(blank=True, default='https://www.youtube.com/@keovuasonghong', null=True, verbose_name='Link YouTube'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_zalo',
            field=models.URLField(blank=True, default='https://zalo.me/3423135266242009757', null=True, verbose_name='Link Zalo OA'),
        ),
    ]
