# Generated by Django 6.1.1 on 2026-09-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_themesettings_footer_doc_1_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='about_commitment_desc',
            field=models.TextField(blank=True, default='SHK Mortar cam kết cung cấp sản phẩm chất lượng, tối ưu chi phí và dịch vụ chu đáo; chúng tôi lấy khách hàng làm trọng tâm của mọi sự phát triển, liên tục cập nhật và chuyển mình để phù hợp với nhu cầu của khách hàng mục tiêu.', verbose_name='Nội dung Cam kết'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_commitment_title',
            field=models.CharField(blank=True, default='Cam kết của chúng tôi', max_length=255, verbose_name='Tiêu đề Cam kết'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_gallery_title',
            field=models.CharField(blank=True, default='Thư viện ảnh SHK', max_length=255, verbose_name='Tiêu đề Thư viện ảnh'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_hero_title',
            field=models.CharField(blank=True, default='Về chúng tôi', max_length=255, verbose_name='Tiêu đề Banner Đầu trang'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_intro_content',
            field=models.TextField(blank=True, default='Công ty TNHH Keo Vữa Sông Hồng (SHK Mortar) được thành lập năm 2025, hoạt động trong lĩnh vực sản xuất và phân phối vật liệu xây dựng, với nhà máy đầu tiên đặt tại Hưng Yên, có quy mô hơn 3.000 m².\n\nNhà máy được đầu tư máy móc hiện đại, hệ thống sản xuất bán tự động và quy trình vận hành bài bản, với hai dây chuyền chuyên sản xuất vữa khô trộn sẵn, keo dán gạch và cát tự nhiên sấy khô, đáp ứng đa dạng nhu cầu của thị trường.\n\nSở hữu đội ngũ giàu kinh nghiệm và am hiểu thực tiễn ngành vật liệu xây dựng, SHK Mortar chú trọng kiểm soát chất lượng từ nguồn nguyên liệu đầu vào đến quá trình sản xuất, nhằm tạo ra những sản phẩm ổn định, chất lượng và phù hợp với yêu cầu thi công.\n\nVới lợi thế về vị trí nhà máy, nguồn nguyên vật liệu dồi dào và năng lực sản xuất, Keo Vữa Sông Hồng hướng tới xây dựng hệ thống cung ứng vật liệu xây dựng chất lượng, vận chuyển nhanh chóng và dịch vụ hậu mãi chuyên nghiệp, trở thành đối tác tin cậy của khách hàng và các đơn vị thi công.', verbose_name='Nội dung các đoạn văn giới thiệu'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/about/', verbose_name='Ảnh giới thiệu chung'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_main_heading',
            field=models.CharField(blank=True, default='Giới thiệu Công ty TNHH Keo Vữa Sông Hồng', max_length=255, verbose_name='Tiêu đề chính giới thiệu'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_statement_col1',
            field=models.TextField(blank=True, default='Chúng tôi mang đến hệ sản phẩm vật liệu xây dựng tối ưu cho thi công, giúp người thợ đơn giản hóa quy trình, tiết kiệm thời gian và nâng cao hiệu quả công việc. Thay thế những hạn chế của phương pháp truyền thống bằng các giải pháp vật liệu hiện đại, ổn định và phù hợp với yêu cầu ngày càng cao của công trình.', verbose_name='Thông điệp - Cột trái'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_statement_col2',
            field=models.TextField(blank=True, default='Đồng thời không ngừng mở rộng và đồng hành cùng hệ thống đại lý, kết nối sâu hơn với các đội thợ và nhà thầu từ quy mô vừa đến nhỏ. Bằng việc đưa giải pháp vật liệu chất lượng đến từng công trình, từng ngôi nhà, góp phần kiến tạo hàng vạn công trình bền vững, hiện thực hóa sứ mệnh "Khởi nguồn cho hàng vạn công trình bền vững".', verbose_name='Thông điệp - Cột phải'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_statement_heading',
            field=models.CharField(blank=True, default='Sự khởi nguồn của mọi công trình bền vững', max_length=255, verbose_name='Tiêu đề Thông điệp'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_story_content',
            field=models.TextField(blank=True, default='SHK Mortar ra đời từ mong muốn giúp người thợ thi công hiệu quả hơn — nhanh hơn, tiết kiệm hơn và bền vững hơn. Từ hành trình nghiên cứu, hoàn thiện công thức phối trộn đến đồng hành cùng đại lý, đội thợ và nhà thầu, chúng tôi tạo ra những giải pháp vật liệu phù hợp với thực tế, góp phần kiến tạo những công trình trọn vẹn và bền vững.', verbose_name='Nội dung Câu chuyện thương hiệu'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_story_heading',
            field=models.CharField(blank=True, default='Câu chuyện thương hiệu', max_length=255, verbose_name='Tiêu đề Câu chuyện thương hiệu'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_story_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/about/', verbose_name='Ảnh Câu chuyện thương hiệu'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_vision_desc',
            field=models.TextField(blank=True, default='Trở thành thương hiệu vữa khô trộn sẵn và keo dán gạch hàng đầu trên thị trường, mở rộng hệ thống phân phối đại lý tới khắp các tỉnh thành tại Việt Nam.', verbose_name='Nội dung Tầm nhìn'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_vision_title',
            field=models.CharField(blank=True, default='Tầm nhìn', max_length=255, verbose_name='Tiêu đề Tầm nhìn'),
        ),
    ]
