# Generated by Django 6.1.1 on 2026-09-16 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_themesettings_about_commitment_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='theme/about_gallery/', verbose_name='Ảnh (tải lên)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ảnh (URL ngoài)')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Chú thích')),
                ('ratio', models.CharField(choices=[('square', 'Vuông'), ('tall', 'Đứng cao'), ('big-tall', 'Đứng rất cao'), ('portrait', 'Đứng vừa'), ('landscape', 'Ngang'), ('pano', 'Ngang hẹp'), ('small', 'Nhỏ')], default='square', max_length=20, verbose_name='Tỉ lệ khung ảnh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.themesettings')),
            ],
            options={
                'verbose_name': 'Ảnh Thư viện (Giới thiệu)',
                'verbose_name_plural': 'Ảnh Thư viện (Giới thiệu)',
                'ordering': ['order'],
            },
        ),
    ]
