# Generated by Django 6.1.1 on 2026-09-16 02:50

from django.db import migrations

GALLERY_ITEMS = [
    ('square', 'Nhà máy SHK Mortar', 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&auto=format&fit=crop&q=80'),
    ('tall', 'Thi công thực tế công trình', 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80'),
    ('tall', 'Dự án tòa nhà cao tầng', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80'),
    ('square', 'Cát tự nhiên sấy khô', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80'),
    ('big-tall', 'Dây chuyền tự động hóa 100%', 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80'),
    ('pano', 'Trung tâm kiểm soát mẻ trộn', 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80'),
    ('portrait', 'Kiểm định chuẩn ISO 9001', 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=800&auto=format&fit=crop&q=80'),
    ('portrait', 'Kho hàng & Đóng bao thành phẩm', 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&auto=format&fit=crop&q=80'),
    ('small', 'Kiểm soát chuẩn kỹ thuật', 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=600&auto=format&fit=crop&q=80'),
    ('landscape', 'Không gian giải pháp vật liệu', 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80'),
    ('tall', 'Kiến trúc công trình bền vững', 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80'),
    ('landscape', 'Đồng hành kỹ thuật tại công trình', 'https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?w=800&auto=format&fit=crop&q=80'),
    ('landscape', 'Khởi nguồn công trình bền vững', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80'),
    ('portrait', 'Đồng hành cùng mọi công trình', 'https://images.unsplash.com/photo-1531834685032-c34bf0d84c77?w=800&auto=format&fit=crop&q=80'),
]


def seed_gallery(apps, schema_editor):
    ThemeSettings = apps.get_model('main', 'ThemeSettings')
    AboutGalleryImage = apps.get_model('main', 'AboutGalleryImage')
    theme, _ = ThemeSettings.objects.get_or_create(pk=1)
    if AboutGalleryImage.objects.filter(theme=theme).exists():
        return
    for idx, (ratio, caption, url) in enumerate(GALLERY_ITEMS):
        AboutGalleryImage.objects.create(
            theme=theme,
            image_url=url,
            caption=caption,
            ratio=ratio,
            order=idx,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_aboutgalleryimage'),
    ]

    operations = [
        migrations.RunPython(seed_gallery, noop_reverse),
    ]
