# Generated by Django 6.1.1 on 2026-09-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_seed_about_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/products/', verbose_name='Ảnh danh mục 1'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_1_link',
            field=models.CharField(blank=True, default='/san-pham/#cat-vua-kho-tron-san', max_length=255, verbose_name='Đường dẫn danh mục 1'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_1_title',
            field=models.CharField(blank=True, default='Vữa khô trộn sẵn', max_length=255, verbose_name='Tên danh mục 1'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/products/', verbose_name='Ảnh danh mục 2'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_2_link',
            field=models.CharField(blank=True, default='/san-pham/#cat-vua-xay-trat-aac', max_length=255, verbose_name='Đường dẫn danh mục 2'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_2_title',
            field=models.CharField(blank=True, default='Vữa xây trát AAC', max_length=255, verbose_name='Tên danh mục 2'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/products/', verbose_name='Ảnh danh mục 3'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_3_link',
            field=models.CharField(blank=True, default='/san-pham/#cat-keo-dan-gach-da', max_length=255, verbose_name='Đường dẫn danh mục 3'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_3_title',
            field=models.CharField(blank=True, default='Keo dán gạch', max_length=255, verbose_name='Tên danh mục 3'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_4_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/products/', verbose_name='Ảnh danh mục 4'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_4_link',
            field=models.CharField(blank=True, default='/san-pham/#cat-cat-sach-say-kho', max_length=255, verbose_name='Đường dẫn danh mục 4'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='prod_cat_4_title',
            field=models.CharField(blank=True, default='Cát sấy khô', max_length=255, verbose_name='Tên danh mục 4'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='products_badge',
            field=models.CharField(blank=True, default='Khám phá', max_length=100, verbose_name='Thẻ phụ (Badge)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='products_btn_link',
            field=models.CharField(blank=True, default='/san-pham/#plStickyNav', max_length=255, verbose_name='Đường dẫn nút xem tất cả'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='products_btn_text',
            field=models.CharField(blank=True, default='Xem tất cả sản phẩm', max_length=100, verbose_name='Chữ trên nút xem tất cả'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='products_title',
            field=models.CharField(blank=True, default='Danh mục sản phẩm', max_length=255, verbose_name='Tiêu đề Danh mục sản phẩm'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='show_products',
            field=models.BooleanField(default=True, verbose_name='Hiển thị Module Danh mục sản phẩm'),
        ),
    ]
