# Generated by Django 6.1.1 on 2026-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_themesettings_prod_cat_1_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('dan-dung', 'Dự án dân dụng'), ('cong-nghiep', 'Dự án công nghiệp')], default='dan-dung', max_length=20, verbose_name='Loại dự án'),
        ),
    ]
