# Generated by Django 6.1.1 on 2026-09-23 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='calculator_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/backgrounds/', verbose_name='Ảnh nền Banner Ước tính vật liệu'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='consultation_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/consultation/', verbose_name='Ảnh minh hoạ Đăng ký tư vấn (phòng Lab)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='phong_su_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/backgrounds/', verbose_name='Ảnh nền Banner Phóng sự thực tế'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_doc_1_link',
            field=models.CharField(blank=True, default='/chinh-sach-va-dieu-khoan/', max_length=255, verbose_name='Đường dẫn tài liệu 1'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_doc_1_title',
            field=models.CharField(blank=True, default='Chính sách và Điều khoản', max_length=150, verbose_name='Tên tài liệu 1'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_doc_2_link',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Đường dẫn tài liệu 2'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_doc_2_title',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Tên tài liệu 2'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_doc_3_link',
            field=models.CharField(blank=True, default='/e-catalog/?doc=ho-so-nang-luc', max_length=255, verbose_name='Đường dẫn tài liệu 3'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_doc_4_link',
            field=models.CharField(blank=True, default='/e-catalog/', max_length=255, verbose_name='Đường dẫn tài liệu 4'),
        ),
        migrations.CreateModel(
            name='QualityCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề chứng chỉ / Giấy kiểm nghiệm')),
                ('image', models.ImageField(upload_to='theme/certificates/', verbose_name='File ảnh chứng chỉ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_certificates', to='main.themesettings', verbose_name='Cài đặt giao diện')),
            ],
            options={
                'verbose_name': 'Giấy chứng nhận / Kiểm định chất lượng',
                'verbose_name_plural': 'Giấy chứng nhận / Kiểm định chất lượng',
                'ordering': ['order', 'id'],
            },
        ),
    ]
