# Generated by Django 6.1.1 on 2026-09-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_themesettings_calculator_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='consultation_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/backgrounds/', verbose_name='Ảnh nền Banner Đăng ký tư vấn'),
        ),
    ]
