# Generated by Django 6.1.1 on 2026-09-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_themesettings_consultation_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='about_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/banners/', verbose_name='Ảnh Hero Banner - Trang Giới thiệu'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='calculator_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/banners/', verbose_name='Ảnh Hero Banner - Trang Công cụ tính'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='catalogue_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/banners/', verbose_name='Ảnh Hero Banner - Trang E-Catalogue'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='default_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/banners/', verbose_name='Ảnh Hero Banner mặc định (dùng chung các trang)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='distributors_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/banners/', verbose_name='Ảnh Hero Banner - Trang Đại lý'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='news_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/banners/', verbose_name='Ảnh Hero Banner - Trang Tin tức'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='policy_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/banners/', verbose_name='Ảnh Hero Banner - Trang Chính sách'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='products_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/banners/', verbose_name='Ảnh Hero Banner - Trang Sản phẩm'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='projects_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/banners/', verbose_name='Ảnh Hero Banner - Trang Dự án'),
        ),
    ]
