# Generated by Django 6.1.1 on 2026-09-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_themesettings_about_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='dealer_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme/dealer/', verbose_name='Ảnh poster bên trái form đăng ký'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dealer_submit_btn_text',
            field=models.CharField(blank=True, default='Đăng ký đại lý', max_length=100, verbose_name='Chữ trên nút gửi biểu mẫu'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dealer_subtitle',
            field=models.CharField(blank=True, default='Cơ hội trở thành đối tác chiến lược của SHK Mortar!', max_length=500, verbose_name='Phụ đề / Khẩu hiệu trang'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dealer_support_email',
            field=models.CharField(blank=True, default='admin@keovuasonghong.vn', max_length=150, verbose_name='Email nhận hỗ trợ'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dealer_support_phone',
            field=models.CharField(blank=True, default='+84 938 016 788 / +84 386 360 797', max_length=100, verbose_name='Số điện thoại hỗ trợ'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dealer_support_subtitle',
            field=models.TextField(blank=True, default='Vui lòng liên hệ với đội ngũ của chúng tôi\nđể nhận được sự hỗ trợ nhanh chóng nhất', verbose_name='Phụ đề khối hỗ trợ'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dealer_support_title',
            field=models.CharField(blank=True, default='Yêu cầu hỗ trợ', max_length=255, verbose_name='Tiêu đề khối hỗ trợ'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dealer_support_zalo',
            field=models.CharField(blank=True, default='https://zalo.me/3423135266242009757', max_length=255, verbose_name='Đường dẫn Zalo OA hỗ trợ'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dealer_support_zalo_name',
            field=models.CharField(blank=True, default='Công ty TNHH Keo Vữa Sông Hồng', max_length=255, verbose_name='Tên hiển thị Zalo OA'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dealer_title',
            field=models.CharField(blank=True, default='ĐĂNG KÝ ĐẠI LÝ', max_length=255, verbose_name='Tiêu đề trang đăng ký'),
        ),
    ]
