# Generated by Django 6.1.1 on 2026-10-06 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_themesettings_dealer_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Để trống nếu đây là đại lý chính. Chọn đại lý cấp trên để đây trở thành đại lý con.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.distributor', verbose_name='Đại lý cấp trên'),
        ),
    ]
