# Generated by Django 6.1.1 on 2026-10-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_distributor_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='description',
            field=models.TextField(blank=True, help_text='Nội dung bài viết giới thiệu hiển thị ở trang chi tiết. Xuống dòng để tách đoạn.', verbose_name='Giới thiệu đại lý'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='warehouse_address',
            field=models.TextField(blank=True, help_text='Để trống sẽ dùng địa chỉ chính.', verbose_name='Địa chỉ kho'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='zalo_link',
            field=models.CharField(blank=True, help_text='VD: 0938016788 hoặc https://zalo.me/0938016788. Dùng để tạo mã QR Zalo. Để trống sẽ lấy số hotline đầu tiên.', max_length=300, verbose_name='Zalo (số điện thoại hoặc link)'),
        ),
    ]
