# Generated by Django 6.1.1 on 2026-10-06 08:31

from django.db import migrations, models


def fill_slugs(apps, schema_editor):
    from main.models import vietnamese_slugify
    Distributor = apps.get_model('main', 'Distributor')
    used = set()
    for d in Distributor.objects.order_by('pk'):
        base = vietnamese_slugify(d.name) or 'dai-ly'
        slug, n = base, 1
        while slug in used:
            n += 1
            slug = f'{base}-{n}'
        used.add(slug)
        Distributor.objects.filter(pk=d.pk).update(slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_distributor_article_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='slug',
            field=models.SlugField(blank=True, help_text='Phần đường dẫn của trang chi tiết, VD: cong-ty-quang-minh. Để trống sẽ tự tạo từ tên đại lý.', max_length=300, verbose_name='Đường dẫn (URL)'),
        ),
        migrations.RunPython(fill_slugs, migrations.RunPython.noop),
    ]
