# Generated by Django 6.1.1 on 2026-10-06 08:34

import django.db.models.deletion
from django.db import migrations, models


def copy_details(apps, schema_editor):
    Distributor = apps.get_model('main', 'Distributor')
    Detail = apps.get_model('main', 'DistributorDetail')
    for d in Distributor.objects.order_by('pk'):
        Detail.objects.create(
            distributor=d,
            slug=d.slug or f'dai-ly-{d.pk}',
            content=''.join(f'<p>{line.strip()}</p>' for line in (d.description or '').splitlines() if line.strip()),
            warehouse_address=d.warehouse_address or '',
            zalo_link=d.zalo_link or '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_distributor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='VD: cong-ty-quang-minh. Để trống sẽ tự tạo từ tên đại lý.', max_length=300, unique=True, verbose_name='Đường dẫn (URL)')),
                ('title', models.CharField(blank=True, help_text='Để trống sẽ dùng tên đại lý.', max_length=400, verbose_name='Tiêu đề trang')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung bài viết')),
                ('warehouse_address', models.TextField(blank=True, help_text='Để trống sẽ dùng địa chỉ chính của đại lý.', verbose_name='Địa chỉ kho')),
                ('zalo_link', models.CharField(blank=True, help_text='VD: 0938016788 hoặc https://zalo.me/0938016788. Để trống sẽ lấy số hotline đầu tiên.', max_length=300, verbose_name='Zalo (số điện thoại hoặc link)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('distributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='main.distributor', verbose_name='Đại lý')),
            ],
            options={
                'verbose_name': 'Chi tiết đại lý',
                'verbose_name_plural': 'Chi tiết đại lý',
                'ordering': ['distributor__province', 'distributor__name'],
            },
        ),
        migrations.RunPython(copy_details, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='distributor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='warehouse_address',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='zalo_link',
        ),
    ]
