# Generated by Django 6.1.1 on 2026-10-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_distributor_detail_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributordetail',
            options={'ordering': ['distributor__province', 'distributor__name'], 'verbose_name': 'Danh mục đại lý', 'verbose_name_plural': 'Danh mục đại lý'},
        ),
    ]
