# Generated by Django 6.1.1 on 2026-10-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_rename_detail_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='parent',
        ),
    ]
