# Generated by Django 6.1.1 on 2026-10-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_remove_distributor_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributordetail',
            name='extra_contacts',
            field=models.JSONField(blank=True, default=list, verbose_name='Thông tin liên hệ thêm'),
        ),
    ]
