# Generated by Django 6.1.1 on 2026-10-09 07:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_distributor_extra_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='catalogues/files/', verbose_name='File PDF'),
        ),
        migrations.AlterField(
            model_name='product',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='products/certificates/', verbose_name='Chứng chỉ chất lượng (PDF)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ecatalog_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='products/ecatalog/', verbose_name='File E-catalog (PDF)'),
        ),
    ]
